language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER Wycliffe WITH PASSWORD 'password1234';" -U postgres
  - flask init-db
script:
 - export FLASK_ENV=testing
 - coverage run --source=app -m pytest && coverage report

after_success:
  - coveralls
