language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt

  - pip install coveralls

env:
  - FLASK_VERSION=1.0.2

script:
 - pytest --cov app/tests/v1

  - coveralls

after_success:
  - coveralls
